### ISSUE TITLE
Armazenamento do token e informações do usuário

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#12]
Olá comunidade, quero abrir uma discussão pra chegarmos a um ponto no quesito de armazenamento das informações retornadas no login. token e outros dados. Atualmente eu sempre salvei dados que precisam ficar um tempo no lado do client no **local storage.** Gostaria de alternativas mais seguras caso essa não seja e também pra o token, expiração e etc.

**Comment by raffacabofrio** [comment]
Eu também armazenaria no local storage.

**Comment by 13Nunes** [comment]
Eu sempre armazenei no localStorage. Claro que no início eu pensava que o token era criptografado, mas depois conversando com um amigo meu também consultor descobri que ele é apenas assinado. Intrigado com essa informação pesquisei um pouco e percebi que não difere muito em questões de segurança de uma autenticação por sessão no servidor. Afinal para roubar o seu token o indivíduo teria que ter acesso ao seu computador.

**Comment by gustavomcastro** [comment]
Aproveitando a discussão.... Depende muito de como irá funcionar o sistema... Se o cara só poderá abrir uma sessão por vez indico colocar na Session Store, pois fica armazenado comente naquela sessao aberta, não sendo possível o acesso atraves de outras abas...

**Comment by 13Nunes** [comment]
Uma questão que enfrentei recentemente é que questão do logoff.
Primariamente eu criei tokens com 24 horas de validade, armazenados em local storage do cliente e removidos do mesmo em caso de logoff.
Todavia, acabei de receber um pentest do cliente informando que por ser possível reaproveitar o token mesmo deletado eu teria que "fazer algo" para otimizar a segurança do projeto.

Com uma pesquisa básica encontramos dois métodos: mitigar o problema reduzindo o tempo de validade do token para algo em torno de 15 minutos a 2 horas. Ou criar uma blacklist de token inválidos e implementar isso no seu sistema de autenticação. Logicamente para não perder performance a solução utiliza Redis.

Qual a opinião de vocês ?
