### ISSUE TITLE
BUG: Verificação de token.

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#124]
Existe um pequeno bug na verificação de expiração do token no front-end, segue o fluxo.

- Acesso ao /login, é verificado se existe o token no local storage, caso sim ele verifica a validade desse token no próprio front-end, nesse caso ele passou, logo após isso ele faz a requisição para busca de dados do usuário, porém a API retorna 401, então temos um problema em alguma das partes em relação a verificação da validade, estou investigando esse problema, se alguém de back-end puder dar uma atenção tbm.

![image](https://user-images.githubusercontent.com/26348646/72365867-d9502c00-36d7-11ea-8192-f4ca441bac45.png)

Paliativo: Enquanto isso, vou criar um fluxo condicional básico, quando rolar o 401 ele terá o token do storage removido e terá que logar novamente

**Comment by DavideCarvalho** [comment]
Tanto a criação quanto a validação do token é feita pela própria biblioteca de JWT que o Nest possui, como você ta validando o jwt?

**Comment by DavideCarvalho** [comment]
Essa é a biblioteca que o Nest usa por de baixo dos panos: https://www.npmjs.com/package/jsonwebtoken. Se vocês querem fazer essa validação no front, talvez usar uma lib de JWT seja melhor

**Comment by portothree** [comment]
Acredito ser melhor mandar um request em cada rota pra verificar se esse token jwt do localstorage ainda está valido, se o server side sempre checa o jwt, a vue-route não vai ser populada pela call da api.
Vou clonar aqui e dar uma olhada também.

**Comment by DavideCarvalho** [comment]
O interceptor do front deveria validar se o retorno é um Unauthorized, se for, ele faz a reautenticação com o refresh token e manda a mesma requisição de novo

**Comment by DavideCarvalho** [comment]
Sigam esse exemplo daqui: https://stackoverflow.com/questions/51646853/automating-access-token-refreshing-via-interceptors-in-axios

**Comment by DavideCarvalho** [comment]
Perceba que se for 401

> Sigam esse exemplo daqui: https://stackoverflow.com/questions/51646853/automating-access-token-refreshing-via-interceptors-in-axios

Perceba que se for 401, ele faz a chamada para a api de refresh token, salva o token novo e depois faz a mesma requisição

**Comment by andrews-felipe** [comment]
O front-end já faz isso ao acessar uma rota ele verifica a autenticidade do token caso for válido ele busca as informações do usuário, a questão é, recebemos uma propriedade no login chamada `expiresIn ` então, devemos fazer uma validação no front pra saber se o token expirou e assim só depois enviar a requisição?

**Comment by andrews-felipe** [comment]
> Acredito ser melhor mandar um request em cada rota pra verificar se esse token jwt do localstorage ainda está valido, se o server side sempre checa o jwt, a vue-route não vai ser populada pela call da api.
> Vou clonar aqui e dar uma olhada também.

Então, como é SSR, ficou meio estranho fazer isso usando o localstorage, mas eu pretendo refinar depois o código, a implementação está pronta.

**Comment by DavideCarvalho** [comment]
> O front-end já faz isso ao acessar uma rota ele verifica a autenticidade do token caso for válido ele busca as informações do usuário, a questão é, recebemos uma propriedade no login chamada `expiresIn ` então, devemos fazer uma validação no front pra saber se o token expirou e assim só depois enviar a requisição?

Não, o front não deve validar o token, vocês devem saber que a sessão do usuário expirou pelo statusCode 401 (Unauthorized), nada mais

**Comment by DavideCarvalho** [comment]
Vocês validarem e depois fazerem a requisição pro back pode dar problema, porque pode estar valido quando vocês checarem e quando chegar pra mim pode não estar mais, então o front deve confiar a validação apenas ao back

**Comment by andrews-felipe** [comment]
> Vocês validarem e depois fazerem a requisição pro back pode dar problema, porque pode estar valido quando vocês checarem e quando chegar pra mim pode não estar mais, então o front deve confiar a validação apenas ao back

O que o front-end faz hoje é 
Ao acessar a aplicação, ele faz uma verificação se existe uma sessão iniciada,
caso não, ele verifica se existe um token no localStorage, faz a validação da "**validade temporal**" desse token, usando a propriedade expiriesIn, **isso não quer dizer que ele tenha acesso ainda**, vamos lá, caso o token for válido nessa "**validação tempora**l" ele vai tentar fazer uma requisição no back-end pr a pegar as informações, se nesse caso a resposta for 200 ele dá o acesso, caso não, terá que se logar novamente.

**Comment by DavideCarvalho** [comment]
Fiz a implementação sem testar, se quiserem testar em alguma branch, aqui no trampo é ruim de ficar saindo da vpn pra testar as coisas da NewSchool

```javascript
http.interceptors.response.use(
  response => response,
  async error => {
    if (error.response.status === 401) {
      const clientCredentials = utils.getPasswordCredentials()
      const body = utils.toFormData({
        grant_type: 'refresh_token',
        refresh_token: 'refresh_token',
      })
      const { data } = await http.post(process.env.endpoints.LOGIN, body, {
        headers: { Authorization: clientCredentials },
      })
      localStorage.setItem('auth', JSON.stringify(data))
      const requestConfig = error.config
      return http(requestConfig)
    }
    return Promise.reject(error)
  },
)
```

**Comment by DavideCarvalho** [comment]
> > Vocês validarem e depois fazerem a requisição pro back pode dar problema, porque pode estar valido quando vocês checarem e quando chegar pra mim pode não estar mais, então o front deve confiar a validação apenas ao back
> 
> O que o front-end faz hoje é
> Ao acessar a aplicação, ele faz uma verificação se existe uma sessão iniciada,
> caso não, ele verifica se existe um token no localStorage, faz a validação da "**validade temporal**" desse token, usando a propriedade expiriesIn, **isso não quer dizer que ele tenha acesso ainda**, vamos lá, caso o token for válido nessa "**validação tempora**l" ele vai tentar fazer uma requisição no back-end pr a pegar as informações, se nesse caso a resposta for 200 ele dá o acesso, caso não, terá que se logar novamente.

Cês não precisam testar se o token dele atual está válido, até porque em produção o accessToken vai ter uma duração muito pequena - de 5 a 10 minutos. Se o cara já tiver um auth no localStorage, bate com o refresh_token dele no back, se der pau redireciona pro login.

**Comment by DavideCarvalho** [comment]
Como o @pethersonmoreno disse, a PR dele não é pro refresh token, então acho que alguém deveria abir uma PR pra isso
