### ISSUE TITLE
BUG : Client_credentials

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#127]
Todas as vezes que a aplicação dorme(no heroku) e é levantada, acontece alguma modificação no banco, que impossibilita novas requisições

![image](https://user-images.githubusercontent.com/26348646/72387683-d454a200-3702-11ea-85cc-04562ed69ea1.png)

Esse erro é recorrente.

**Comment by DavideCarvalho** [comment]
Então, como o banco de dev ta liberado pra qualquer um que queira usar, não conseguimos validar onde é isso direito.
Na entidade, temos 2 campos que são alterados sempre que damos update na tabela: updatedAt e version.
Se fosse via código, toda vez que alterasse o client credentials iria ser somado +1 no version e o updatedAt seria atualizado.
Possibilidades:
- Alguém de má fé está alterando
- Alguém possui uma versão do banco mais antiga

**Comment by DavideCarvalho** [comment]
Podemos fechar? Isso é mais um caso de proteger os ambientes do que código mesmo
