### ISSUE TITLE
Erro 500 ao excluir o curso

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#132]
![image](https://user-images.githubusercontent.com/26348646/72479271-c8381580-37d2-11ea-893f-9517ca31afbe.png)

**Comment by DavideCarvalho** [comment]
Cê ta tentando deletar um curso que tem pessoas referênciadas

**Comment by andrews-felipe** [comment]
> Cê ta tentando deletar um curso que tem pessoas referênciadas

em quais circunstancias o admin pode excluir o um curso, tem que ver o card

**Comment by DavideCarvalho** [comment]
Relaxa, estamos arrumando isso
