### ISSUE TITLE
Erro 404 na busca do curso por slug

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#133]
![image](https://user-images.githubusercontent.com/26348646/72480542-7d200180-37d6-11ea-9c47-d70bc35dfcae.png)

**Comment by DavideCarvalho** [comment]
E único curso com slug é esse: habilidades-do-futuro

**Comment by pethersonmoreno** [comment]
> E único curso com slug é esse: habilidades-do-futuro

Esse habilidades-do-futuro eu coloquei via um update manual no banco de dados para o detalhe do curso que eu iniciei o ajuste
