### ISSUE TITLE
BUG: i18n

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolApp/newschool-frontend#137]
O i18n está interferindo no roteamento, ao atualizar o projeto
o nome de algumas rotas, são modificados para /rota__pt

![image](https://user-images.githubusercontent.com/26348646/72536318-c6b13080-3858-11ea-8e3c-70abb25eafa3.png)

ao comentar esse trecho a página carrega normalmente

![image](https://user-images.githubusercontent.com/26348646/72536365-ddf01e00-3858-11ea-90ad-acbe62b89620.png)

**Comment by pethersonmoreno** [comment]
Está sendo utilizado o nome das rotas para navegação?
Caso contrário não afetaria o aplicativo.

**Comment by pethersonmoreno** [comment]
Apesar de não perceber problema afetando o aplicativo os ajustes do i18n, consegui desabilitar o i18n de afetar as rotas, mas ainda funcionando a tradução das mensagens do Backend.
Os ajustes foram feitos na PR: https://github.com/NewSchoolBR/newschool-frontend/pull/141
