### ISSUE TITLE
Solicitação na recuperação de senha (erro no Backend)

### ISSUE THREAD

**Issue by joaogabriel1702** [NewSchoolApp/newschool-frontend#147]
Quando o usuario clica no link recebido no seu email para trocar sua senha (uma vez que ele esqueceu ela) ele vai para a primeira tela abaixo. No momento que ele digita a nova senha e a confirmação da mesma senha ele clica em "redefinir senha" e o erro que ocorre esta na segunda imagem.

![image](https://user-images.githubusercontent.com/38577266/72674521-8a4b2380-3a56-11ea-819c-7af6e6c1444f.png)

![image](https://user-images.githubusercontent.com/38577266/72674486-faa57500-3a55-11ea-97d5-4ecd1b546c6b.png)

**Comment by andrews-felipe** [comment]
@fmomoreira
