### ISSUE TITLE
Botões do login perdem o layout correto

### ISSUE THREAD

**Issue by wantero** [NewSchoolApp/newschool-frontend#149]
Ao entrar na tela de login, todos os botões possuem o mesmo tamanho. Após realizar o logout o botão "Esqueceu sua senha?" perde o seu tamanho correto e todos os botões mudam de fonte.

1. Tela quando entramos no sistema.

![Tela correta do login quando entra no sistema.](https://user-images.githubusercontent.com/12854717/72679829-ce0f4e80-3a91-11ea-8843-275d2c6aa9aa.png)

2. Tela após entrar no sistema e clicar no botão sair do menu outros.

![Tela incorreta do login após logado e clicar no botão de sair.](https://user-images.githubusercontent.com/12854717/72679832-d2d40280-3a91-11ea-9b91-2ff77c40cc80.png)

**Comment by ViniciusDalmazzo** [comment]
@wantero Eu estava implementando os botões de redes sociais na tela de login e não sei se indiretamente o erro foi corrigido mas não consegui simular.. segue video dos testes.

Minha branch com as alterações: https://github.com/ViniciusDalmazzo/newschool-frontend/tree/login-redes-sociais


https://www.loom.com/share/327fa9cb6ab84c33a6c2f117077d7b80

**Comment by wantero** [comment]
Ok. Se com os seus botões esse erro não ocorrer mais, a gente fecha a issue.
