### ISSUE TITLE
Ao tentar recuperar senha é emitido Network Error

### ISSUE THREAD

**Issue by filipefelice** [NewSchoolApp/newschool-frontend#196]
🔸Tipo: Funcionalidade

🔸Descrição: Ao tentar recuperar senha é emitido Network Error

🔸Mensagem Error: Network Error

🔸Fluxo: tela de login > recuperar senha > colocar e-mail e clicar em redefinir senha.

🔹Imagens: ![image](https://user-images.githubusercontent.com/36074458/73174239-0217ee80-40e6-11ea-9c48-7d4827879778.png)

🔹Endpoint e Response: 
![image](https://user-images.githubusercontent.com/36074458/73174339-3d1a2200-40e6-11ea-8194-03da0435b9a9.png)

**Comment by andrews-felipe** [comment]
https://github.com/NewSchoolApp/newschool-frontend/pull/208
