### ISSUE TITLE
Meu certificado contém algumas informações inválidas e Share não funciona

### ISSUE THREAD

**Issue by filipefelice** [NewSchoolApp/newschool-frontend#197]
**Tipo:** Funcionalidade

**Descrição:** Carga horária está com 0 na duração, período não está com range de/até, titulo Newschool incorreto trocar para New School e compartilhamento nas redes sociais está indo com o link errado(colocar url corrente).

**Mensagem:**

**Fluxo:** login > home > meus certificados > selecionar certificado

**Imagens:** 

![PHOTO-2020-01-26-13-10-34](https://user-images.githubusercontent.com/36074458/73175704-8ae45980-40e9-11ea-9053-6ea7da16f4fc.jpg)

**Comment by oliveirabalsa** [comment]
Filipe, aqui no meu local essa questão da carga horária esta normal, talvez esse curso tenha sido registrado com carga horaria 0...

**Comment by andrews-felipe** [comment]
@cidcair
