### ISSUE TITLE
Botão compartilhar está compartilhando a URL errada.

### ISSUE THREAD

**Issue by filipefelice** [NewSchoolApp/newschool-frontend#199]
**Tipo:** Funcionalidade

**Descrição:** Botão compartilhar está compartilhando a URL errada e com a tag #missaonewschoolapp, precisa removerhashtag e compartilhar o curso corretamente.

**Fluxo:** tela de login > home > clicar em compartilhar no curso / tela de login > home > meus certificados > certificado > ompartilhar certificado.

🔹Imagens: 
![image](https://user-images.githubusercontent.com/36074458/73179368-f7fbed00-40f1-11ea-9155-75e1daadc957.png)

**Comment by thii777** [comment]
@thi777

**Comment by andrews-felipe** [comment]
https://github.com/NewSchoolApp/newschool-frontend/pull/208
