### ISSUE TITLE
Estilo no card de cursos.

### ISSUE THREAD

**Issue by thii777** [NewSchoolApp/newschool-frontend#203]
### Melhorias no layout dos cursos em home

#### Componente share:
O componente de compartilhamento esta dividindo espaço com o titulo do card, quando o correto seria ele ficar por cima, talvez um position: absolute resolva, 

#### Espaço entre o nome e o titulo
Essas duas linhas estão muito juntas, precisa afastar um pouco um do outro, talvez um space letter para afastar um pouco uma letra da outra possa ser analisado.

![home](https://user-images.githubusercontent.com/51274716/73596490-2d914380-4501-11ea-8302-ce26ff6e6b01.png)

**Comment by andrews-felipe** [comment]
@portothree

**Comment by thii777** [comment]
@dueduardoful

**Comment by dueduardoful** [comment]
> ### Melhorias no layout dos cursos em home
> #### Componente share:
> O componente de compartilhamento esta dividindo espaço com o titulo do card, quando o correto seria ele ficar por cima, talvez um position: absolute resolva,
> 
> #### Espaço entre o nome e o titulo
> Essas duas linhas estão muito juntas, precisa afastar um pouco um do outro, talvez um space letter para afastar um pouco uma letra da outra possa ser analisado.
> 
> ![home](https://user-images.githubusercontent.com/51274716/73596490-2d914380-4501-11ea-8302-ce26ff6e6b01.png)

#204

**Comment by dueduardoful** [comment]
Closes #204
