### ISSUE TITLE
"Entrar com Google" Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by jardelmv** [NewSchoolApp/newschool-frontend#225]
he redirect URI in the request, https://newschoolbr-dev.herokuapp.com/login, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/889053794643-qu89df6ei5u2sncnfmedi39m2ascih3k.apps.googleusercontent.com?project=889053794643

**Comment by pethersonmoreno** [comment]
Thanks @jardelmv by reporting it.
