### ISSUE TITLE
Ajustar cor dos labels e-mail e senha na tela do login ao focar o campo

### ISSUE THREAD

**Issue by pethersonmoreno** [NewSchoolApp/newschool-frontend#58]
Ao focar no campo e-mail ou senha, o label fica quase invisível por causa da cor do texto e da cor do fundo.

![image](https://user-images.githubusercontent.com/22779752/71636953-1bc53380-2c17-11ea-811c-0e90187e9cf9.png)

**Comment by wantero** [comment]
Na página de login o ENTER dentro do campo após o preenchimento também não executa o submit de logar-se, desta forma tem que clicar no botão login para proceder com o login.

**Comment by andrews-felipe** [comment]
Galera, estou pensando em refazer essa tela, não vou demorar muito, apenas pelas questões de estilização. O css dentro desse componente pode afetar outros. Há coisas que não consegui modificar sem alterar o tema diretamente no `nuxt.config` mas isso é facilmente resolvido com o `scoped` também acho que você @pethersonmoreno está com essa view desatualizada, os problemas de cores já estão resolvidos.

Resolução: Refatoração por completa da tela login

**Comment by raffacabofrio** [comment]
Por mim tudo bem. Login e cadastro são as estórias mais importantes. Com elas entregues a gente vai ter mais liberdade/facilidade de validar e desenvolver as demais.

**Comment by wantero** [comment]
Por mim poderia ser depois que fechar os itens do MVP. Sobre o meu comentário acima o mesmo ainda acontece.
