### ISSUE TITLE
Alguns layout ficam desconfigurado após voltar o histórico do navegador

### ISSUE THREAD

**Issue by wantero** [NewSchoolApp/newschool-frontend#68]
Segue [vídeo](https://www.dropbox.com/s/8ugpac13c37nn3c/RPReplay_Final1577993032.mov?dl=0) demonstrando o problema.

A tela também de contribua não está scrollando no iPhone.

**Comment by raffacabofrio** [comment]
Seria bom centralizar no trello. caso ainda não tenha feito.

**Comment by wantero** [comment]
> Seria bom centralizar no trello. caso ainda não tenha feito.

Sim. Estou abrindo aqui e vou abrir o card.
